# Generated by Django 6.0.3 on 2026-07-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_alter_client_options_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.invoice')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.service')),
            ],
        ),
        migrations.CreateModel(
            name='GstBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gst', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoice')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoicelineitem')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('Net Banking', 'Net Banking')], max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.invoice')),
            ],
        ),
    ]



