# Generated by Django 6.0.3 on 2026-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_invoicelineitem_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='rate',
            new_name='gst_amount',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='tax_amount',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='invoicelineitem',
            old_name='line_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
