# Generated by Django 6.0.3 on 2026-07-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gstconfiguration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='gst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.gstconfiguration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
