# Generated by Django 6.0.3 on 2026-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_service_hsn_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
